name: Build and Deploy Frontend Image

on:
  push:
    branches:
      - ci/pipeline
    paths:
      - 'book-network-ui/**'
      - '.github/workflows/*-frontend.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Frontend Docker Image
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # submodules: recursive  # Commenté car book-network-ui n'est plus un sous-module

      - name: Debug directory structure
        run: |
          ls -R
          pwd
          find . -name package.json

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.20.4'

      - name: Build frontend
        run: |
          cd book-network-ui
          npm install
          npm run api-gen
          npm run build -- --configuration production

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract project version
        id: extract_version
        run: |
          cd book-network-ui
          VERSION=$(node -p "require('./package.json').version || '1.0.0'")
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: book-network-ui
          file: book-network-ui/Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/bsn-ui:${{ steps.extract_version.outputs.version }}
            ${{ secrets.DOCKER_USERNAME }}/bsn-ui:latest